### PR TITLE
Fix: short comment following long comment close

### LINKED ISSUE #170: Multiline comments, indent after closing "]]" is unstable
Take this code block:
```lua
--[[
hello
world
]]--
```

Run `Format` and EmmyLuaCodeStyle Style changes it to:
```lua
--[[
poop
crap
]]
   --
```

Format a second time changes it again:
```lua
--[[
poop
crap
]]
--
```

1. Ideally I'd love EmmyLuaCodeStyle to leave the first block unchanged.
2. Even if not, formatted output should probably be stable such that `format(format(code)) == format(code)`

Thanks!

### PR DESCRIPTION
**Pull request by notpeter**
Makes short comment immediately following long comment not add a linebreak. No longer incorrectly indents.

Fixes #170

Before: `--[[]]--`  -> `--[[]]\n    --` -> `--[[]]\n--`
After: `--[[]]--` -> `--[[]] --`

### CODE REVIEW

File: CodeFormatCore/src/Format/Analyzer/LineBreakAnalyzer.cpp [hunk 1]
```diff
@@ -3,6 +3,7 @@
 #include "CodeFormatCore/Format/FormatState.h"
 #include "LuaParser/Lexer/LuaTokenTypeDetail.h"
 #include <algorithm>
+#include <cstdio>
```
Comment (CppCXY) [inline CodeFormatCore/src/Format/Analyzer/LineBreakAnalyzer.cpp:6]: donot need include

File: CodeFormatCore/src/Format/Analyzer/LineBreakAnalyzer.cpp [hunk 2]
```diff
@@ -107,8 +108,14 @@ void LineBreakAnalyzer::ComplexAnalyze(FormatState &f, const LuaSyntaxTree &t) {
...
                         } else {
                             switch (stmt.GetTokenKind(t)) {
-                                case TK_SHORT_COMMENT:
                                 case TK_LONG_COMMENT:
+                                {
+                                    auto nextToken = stmt.GetNextToken(t).GetTokenKind(t);
+                                    if (nextToken == TK_SHORT_COMMENT) {
+                                        break;
+                                    }
+                                }
```
Comment (CppCXY) [inline CodeFormatCore/src/Format/Analyzer/LineBreakAnalyzer.cpp:117]: add comment "// fallthrough"

File: CodeFormatCore/src/Format/Analyzer/LineBreakAnalyzer.cpp (hunk 1 above)
Comment (notpeter) [reply CodeFormatCore/src/Format/Analyzer/LineBreakAnalyzer.cpp]: Oops.

File: CodeFormatCore/src/Format/Analyzer/LineBreakAnalyzer.cpp (hunk 2 above)
Comment (notpeter) [reply CodeFormatCore/src/Format/Analyzer/LineBreakAnalyzer.cpp:117]: done
